version: '3.9'
services:
    pg: 
        image: postgres
        ports: # dev            
            - 127.0.0.1:5432:5432
        environment: 
            - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
            - POSTGRES_DB=${POSTGRES_DB}
        volumes:
            - ./server/db.sql:/docker-entrypoint-initdb.d/db.sql
    pgadmin: #dev
        image: adminer
        ports: 
            - 127.0.0.1:8080:8080
        depends_on: 
            - pg